import { AdminPageHeader, AdminPanel } from "../../admin-shell";
import { Breadcrumbs, DetailGrid, LinkedValue, QuickActionModal, Status, Tabs } from "../../admin-components";
import { bookingById, fraudCases, tickets } from "../../admin-data";

export default async function BookingDetailPage({ params }: { params: Promise<{ bookingId: string }> }) {
  const { bookingId } = await params;
  const booking = bookingById(bookingId);
  return <main className="admin-main"><Breadcrumbs items={[{ label: "Админ", href: "/dashboard" }, { label: "Бронирования", href: "/bookings" }, { label: booking.id }]} /><AdminPageHeader title={booking.id} subtitle={`${booking.client} · ${booking.trip}`} actions={<><QuickActionModal label="Заметка" title="Заметка бронирования">Demo-заметка без backend mutation.</QuickActionModal><QuickActionModal label="Кратко" title="Кратко о бронировании"><DetailGrid items={[["Клиент", booking.client], ["Поездка", booking.trip], ["Статус", <Status key="s" value={booking.status} />]]} /></QuickActionModal></>} /><div className="admin-detail-layout"><AdminPanel className="p-4"><DetailGrid items={[["Клиент", <LinkedValue key="c" href={`/users/${booking.clientId}`}>{booking.client}</LinkedValue>], ["Поездка", <LinkedValue key="t" href={`/trips/${booking.tripId}`}>{booking.trip}</LinkedValue>], ["Места", booking.seats], ["Пожелания", "Quiet pickup, direct driver contact"], ["Багаж", booking.baggage], ["Посадка", booking.pickup], ["Запрошенный выезд", booking.requested], ["Весь автомобиль", booking.wholeCar], ["Статус", <Status key="s" value={booking.status} />], ["Риск", <Status key="r" value={booking.risk} />]]} /></AdminPanel><Tabs tabs={[{ label: "Жизненный цикл", content: <DetailGrid items={[["Requested", booking.requested], ["Driver response", booking.status], ["Payment", "Напрямую с водителем"]]} /> }, { label: "История", content: <DetailGrid items={[["Created", booking.requested], ["Notification", "Delivered"], ["Latest audit", "Preview event"]]} /> }, { label: "Награда", content: <DetailGrid items={[["Reward", booking.reward], ["Related transaction", <LinkedValue key="r" href="/rewards">Открыть награды</LinkedValue>]]} /> }, { label: "Антифрод", content: fraudCases.filter((item) => item.tripId === booking.tripId).map((item) => <Row key={item.id} href="/fraud" title={item.reason} meta={item.risk} />) }, { label: "Поддержка", content: tickets.filter((ticket) => ticket.bookingId === booking.id).map((ticket) => <Row key={ticket.id} href={`/support/${ticket.id}`} title={ticket.subject} meta={ticket.status} />) }]} /></div></main>;
}
function Row({ href, title, meta }: { href: string; title: string; meta: string }) { return <a className="mb-2 grid grid-cols-[1fr_auto] rounded-[8px] border border-[rgb(var(--border))] p-3 text-[rgb(var(--foreground))] no-underline hover:bg-[rgb(var(--surface-muted))]" href={href}><strong>{title}</strong><Status value={meta} /></a>; }