import { AdminPageHeader, AdminPanel } from "../../admin-shell";
import { Breadcrumbs, DetailGrid, LinkedValue, QuickActionModal, Status, Tabs } from "../../admin-components";
import { bookingById, fraudCases, rewards, tickets } from "../../admin-data";

export default async function BookingDetailPage({ params }: { params: Promise<{ bookingId: string }> }) {
  const { bookingId } = await params;
  const booking = bookingById(bookingId);
  return <main className="admin-main"><Breadcrumbs items={[{ label: "Admin", href: "/dashboard" }, { label: "Бронирования", href: "/bookings" }, { label: booking.id }]} /><AdminPageHeader title={booking.id} subtitle={`${booking.client} · ${booking.trip}`} actions={<><QuickActionModal label="Add note" title="Add booking note">Preview note only. Existing backend note endpoint can be attached later.</QuickActionModal><QuickActionModal label="Quick detail" title="Booking quick detail"><DetailGrid items={[["Client", booking.client], ["Trip", booking.trip], ["Status", <Status key="s" value={booking.status} />]]} /></QuickActionModal></>} /><div className="admin-detail-layout"><AdminPanel className="p-4"><DetailGrid items={[["Client", <LinkedValue key="c" href={`/users/${booking.clientId}`}>{booking.client}</LinkedValue>], ["Trip", <LinkedValue key="t" href={`/trips/${booking.tripId}`}>{booking.trip}</LinkedValue>], ["Seat selection", booking.seats], ["Preferences", "Quiet pickup, direct driver contact"], ["Baggage", booking.baggage], ["Pickup", booking.pickup], ["Requested departure", booking.requested], ["Whole-car", booking.wholeCar], ["Status", <Status key="s" value={booking.status} />], ["Risk", <Status key="r" value={booking.risk} />]]} /></AdminPanel><Tabs tabs={[{ label: "Lifecycle", content: <DetailGrid items={[["Requested", booking.requested], ["Driver response", booking.status], ["Payment", "Direct with driver"]]} /> }, { label: "Timeline", content: <DetailGrid items={[["Created", booking.requested], ["Notification", "Delivered"], ["Latest audit", "Preview event"]]} /> }, { label: "Reward status", content: <DetailGrid items={[["Reward", booking.reward], ["Related transaction", <LinkedValue key="r" href="/rewards">Open rewards</LinkedValue>]]} /> }, { label: "Fraud evaluation", content: fraudCases.filter((item) => item.tripId === booking.tripId).map((item) => <Row key={item.id} href="/fraud" title={item.reason} meta={item.risk} />) }, { label: "Support issues", content: tickets.filter((ticket) => ticket.bookingId === booking.id).map((ticket) => <Row key={ticket.id} href={`/support/${ticket.id}`} title={ticket.subject} meta={ticket.status} />) }]} /></div></main>;
}
function Row({ href, title, meta }: { href: string; title: string; meta: string }) { return <a className="mb-2 grid grid-cols-[1fr_auto] rounded-[8px] border border-[rgb(var(--border))] p-3 text-[rgb(var(--foreground))] no-underline hover:bg-[rgb(var(--surface-muted))]" href={href}><strong>{title}</strong><Status value={meta} /></a>; }