import { AdminPageHeader, AdminPanel } from "../../admin-shell";
import { Breadcrumbs, DetailGrid, LinkedValue, QuickActionModal, Status, Tabs } from "../../admin-components";
import { bookings, fraudCases, rewards, tickets, tripById } from "../../admin-data";

export default async function TripDetailPage({ params }: { params: Promise<{ tripId: string }> }) {
  const { tripId } = await params;
  const trip = tripById(tripId);
  const tripBookings = bookings.filter((booking) => booking.tripId === trip.id);
  return <main className="admin-main"><Breadcrumbs items={[{ label: "Admin", href: "/dashboard" }, { label: "Поездки", href: "/trips" }, { label: trip.route }, { label: trip.id }]} /><AdminPageHeader title={trip.route} subtitle={`${trip.departure} · ${trip.driver}`} actions={<><QuickActionModal label="Trip quick detail" title="Trip quick detail"><DetailGrid items={[["Status", <Status key="s" value={trip.status} />], ["Seats", trip.seats], ["Start PIN", trip.startPin]]} /></QuickActionModal><QuickActionModal label="Change status" title="Change trip status">Preview-only action. Backend trip lifecycle action can be attached here.</QuickActionModal></>} /><div className="admin-detail-layout"><AdminPanel className="p-4"><DetailGrid items={[["Driver", <LinkedValue key="d" href={`/drivers/${trip.driverId}`}>{trip.driver}</LinkedValue>], ["Vehicle", "Primary registered vehicle"], ["Status", <Status key="s" value={trip.status} />], ["Departure", trip.departure], ["Seats", trip.seats], ["Bookings", trip.bookings], ["Whole-car", trip.wholeCar], ["Start PIN", <Status key="p" value={trip.startPin} />], ["ETA", trip.eta], ["Risk", <Status key="r" value={trip.risk} />]]} /></AdminPanel><Tabs tabs={[{ label: "Passengers", content: tripBookings.map((booking) => <Row key={booking.id} href={`/users/${booking.clientId}`} title={booking.client} meta={booking.status} />) }, { label: "Bookings", content: tripBookings.map((booking) => <Row key={booking.id} href={`/bookings/${booking.id}`} title={booking.id} meta={booking.seats} />) }, { label: "Timeline", content: <DetailGrid items={[["Published", "Today 08:10"], ["Matched", "Today 08:18"], ["Boarding", trip.status === "Boarding" ? "Active" : "Not active"]]} /> }, { label: "GPS history", content: <DetailGrid items={[["Latest ping", "12:28"], ["Corridor", trip.route], ["ETA foundation", trip.eta]]} /> }, { label: "Fraud flags", content: fraudCases.filter((item) => item.tripId === trip.id).map((item) => <Row key={item.id} href="/fraud" title={item.reason} meta={item.risk} />) }, { label: "Rewards", content: rewards.filter((item) => item.tripId === trip.id).map((item) => <Row key={item.id} href="/rewards" title={item.source} meta={item.status} />) }, { label: "Support", content: tickets.filter((item) => item.tripId === trip.id).map((item) => <Row key={item.id} href={`/support/${item.id}`} title={item.subject} meta={item.priority} />) }, { label: "Matching", content: <DetailGrid items={[["Waitlist relation", "Active demand linked"], ["Fill", "2 seats filled from waitlist"], ["Return", "Return opportunity visible"]]} /> }]} /></div></main>;
}
function Row({ href, title, meta }: { href: string; title: string; meta: string }) { return <a className="mb-2 grid grid-cols-[1fr_auto] rounded-[8px] border border-[rgb(var(--border))] p-3 text-[rgb(var(--foreground))] no-underline hover:bg-[rgb(var(--surface-muted))]" href={href}><strong>{title}</strong><Status value={meta} /></a>; }