import { AdminPageHeader, AdminPanel } from "../../admin-shell";
import { Breadcrumbs, DetailGrid, LinkedValue, QuickActionModal, Status } from "../../admin-components";
import { ticketById } from "../../admin-data";

export default async function SupportDetailPage({ params }: { params: Promise<{ ticketId: string }> }) {
  const { ticketId } = await params;
  const ticket = ticketById(ticketId);
  return <main className="admin-main"><Breadcrumbs items={[{ label: "Admin", href: "/dashboard" }, { label: "Поддержка", href: "/support" }, { label: ticket.id }]} /><AdminPageHeader title={ticket.subject} subtitle={`${ticket.requester} · ${ticket.category}`} actions={<><QuickActionModal label="Reply" title="Reply to requester" action="Send preview reply">Conversation reply action is wired as a modal foundation for the existing support backend.</QuickActionModal><QuickActionModal label="Change status" title="Change support status">Choose a status when the backend mutation is enabled.</QuickActionModal><QuickActionModal label="Assign" title="Assign ticket">Assign to an operator queue.</QuickActionModal><QuickActionModal label="Close" title="Close ticket" action="Close preview">Close is disabled as live mutation in preview.</QuickActionModal></>} /><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><AdminPanel className="overflow-hidden"><div className="border-b border-[rgb(var(--border))] p-4"><h2 className="m-0 text-base font-black">Conversation</h2></div><div className="space-y-3 p-4"><Message who={ticket.requester} text={ticket.subject} /><Message who="Support" text="We are reviewing the trip and booking context. Attachments and audit are visible on the right." /><Message who={ticket.requester} text="Thank you. Please keep the trip team updated." /></div></AdminPanel><AdminPanel className="p-4"><h2 className="m-0 mb-3 text-base font-black">Ticket context</h2><DetailGrid items={[["Requester", <LinkedValue key="u" href={`/users/${ticket.requesterId}`}>{ticket.requester}</LinkedValue>], ["Trip", <LinkedValue key="t" href={`/trips/${ticket.tripId}`}>{ticket.tripId}</LinkedValue>], ["Booking", <LinkedValue key="b" href={`/bookings/${ticket.bookingId}`}>{ticket.bookingId}</LinkedValue>], ["Category", ticket.category], ["Status", <Status key="s" value={ticket.status} />], ["Priority", <Status key="p" value={ticket.priority} />], ["Attachments", "2 preview files"], ["Audit", `Assigned: ${ticket.assigned}`]]} /></AdminPanel></div></main>;
}
function Message({ who, text }: { who: string; text: string }) { return <div className="rounded-[8px] border border-[rgb(var(--border))] bg-[rgb(var(--canvas))] p-3"><div className="text-xs font-black text-[rgb(var(--primary))]">{who}</div><p className="m-0 mt-1 text-sm">{text}</p></div>; }