"use client";

import { useMemo, useState } from "react";
import { AdminPageHeader, AdminPanel, AdminStatusBadge } from "../admin-shell";
import { DataTable, QuickActionModal, Status, Tabs, Toolbar } from "../admin-components";
import { rewards } from "../admin-data";

const drawings = [
  { id: "DRAW-01", prize: "Смартфон", eligibility: "Билеты клиента", window: "10 июн → 18 июн", entries: "1 билет = 1 участие", participants: 128, winners: "На проверке" },
  { id: "DRAW-02", prize: "Приз от партнёра", eligibility: "30 зачётных поездок", window: "20 июн → 30 июн", entries: "10 билетов = 1 участие", participants: 46, winners: "Запланировано" },
];
const milestones = [
  { id: "MS-50", title: "50 зачётных поездок", reward: "20 билетов", status: "Активно", drivers: 34 },
  { id: "MS-Q90", title: "Качество 90 дней", reward: "Партнёрский приз", status: "На проверке", drivers: 12 },
];

type TabKey = "Обзор" | "Розыгрыши" | "Транзакции" | "Цели водителей";

export default function RewardsPage() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("Все статусы");
  const [activeTab, setАктивноTab] = useState<TabKey>("Обзор");
  const rows = useMemo(() => rewards.filter((r) => `${r.id} ${r.owner} ${r.role} ${r.source}`.toLowerCase().includes(query.toLowerCase()) && (filter === "Все статусы" || r.status === filter || r.role === filter || r.risk === filter)), [filter, query]);

  return <main className="admin-main"><AdminPageHeader title="Награды" subtitle="Розыгрыши, транзакции, очередь проверки и цели водителей." actions={<QuickActionModal label="Создать розыгрыш" title="Новый розыгрыш" action="Сохранить"><DrawingForm /></QuickActionModal>} />
    <div className="mb-3 flex flex-wrap gap-2">{(["Обзор", "Розыгрыши", "Транзакции", "Цели водителей"] as TabKey[]).map((tab) => <button key={tab} className={`min-h-9 rounded-[10px] px-3 text-sm font-black ${activeTab === tab ? "bg-[rgb(var(--primary))] text-[rgb(var(--primary-foreground))]" : "border border-[rgb(var(--border))] bg-[rgb(var(--surface))] text-[rgb(var(--text-muted))]"}`} type="button" onClick={() => setАктивноTab(tab)}>{tab}</button>)}</div>
    {activeTab === "Обзор" ? <Overview /> : null}
    {activeTab === "Розыгрыши" ? <Drawings /> : null}
    {activeTab === "Транзакции" ? <AdminPanel className="overflow-hidden"><Toolbar query={query} onQuery={setQuery} filters={["Все статусы", "Клиент", "Водитель", "На проверке", "Начислено", "Отклонено", "Низкий", "Средний", "Высокий"]} activeFilter={filter} onFilter={setFilter} placeholder="Награда, клиент, водитель, источник" count={rows.length} /><DataTable rows={rows} hrefFor={() => "/rewards"} columns={[{ key: "id", label: "Награда", render: (r) => <strong>{r.id}</strong> }, { key: "owner", label: "Кому", render: (r) => `${r.owner} · ${r.role}` }, { key: "source", label: "Источник", render: (r) => r.source }, { key: "trip", label: "Поездка", render: (r) => r.tripId }, { key: "amount", label: "Билеты", render: (r) => r.amount }, { key: "status", label: "Статус", render: (r) => <Status value={r.status} /> }, { key: "risk", label: "Риск", render: (r) => <Status value={r.risk} /> }, { key: "action", label: "Действие", render: (r) => <QuickActionModal label="Проверить" title="Транзакция награды"><p>{r.owner} · {r.source} · {r.amount}</p><p>Проверьте источник, статус и количество билетов. Изменения пока не сохраняются.</p></QuickActionModal> }]} /></AdminPanel> : null}
    {activeTab === "Цели водителей" ? <Milestones /> : null}
  </main>;
}

function Overview() { return <div className="grid gap-4 xl:grid-cols-4"><Summary label="Активные розыгрыши" value="2" tone="info" /><Summary label="На проверке" value="18" tone="warning" /><Summary label="Начисления билетов" value="146" tone="success" /><Summary label="Отклонено / фрод" value="7" tone="danger" /><AdminPanel className="p-4 xl:col-span-2"><h2 className="m-0 text-lg font-black">Операции наград</h2><p className="text-sm font-semibold text-[rgb(var(--text-muted))]">Обзор показывает клиентские и водительские билеты, розыгрыши, рефералы и промокоды в текущем состоянии.</p><div className="grid gap-2 sm:grid-cols-2"><StatusLine label="Билеты клиентов" value="1 284" /><StatusLine label="Водители к цели" value="34" /><StatusLine label="Очередь проверки" value="18" /><StatusLine label="Отклонено антифродом" value="7" /></div></AdminPanel><AdminPanel className="p-4 xl:col-span-2"><h2 className="m-0 text-lg font-black">Состояния проверки</h2><div className="mt-3 grid gap-2"><StatusLine label="Весенняя акция" value="На проверке" /><StatusLine label="Награда по спору о багаже" value="Отклонено" /><StatusLine label="Бонус водителя за качество" value="На проверке" /></div></AdminPanel></div>; }
function Drawings() { return <AdminPanel className="p-4"><div className="grid gap-3 lg:grid-cols-2">{drawings.map((drawing) => <section key={drawing.id} className="rounded-[8px] border border-[rgb(var(--border))] bg-[rgb(var(--canvas))] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="m-0 text-lg font-black">{drawing.prize}</h2><p className="m-0 mt-1 text-sm font-semibold text-[rgb(var(--text-muted))]">{drawing.id} · {drawing.window}</p></div><Status value={drawing.winners} /></div><div className="mt-3 grid gap-2 text-sm"><StatusLine label="Условия" value={drawing.eligibility} /><StatusLine label="Правило билетов" value={drawing.entries} /><StatusLine label="Участники" value={String(drawing.participants)} /></div><div className="mt-3 flex gap-2"><QuickActionModal label="Детали приза" title="Детали приза"><p>{drawing.prize}</p><p>Здесь доступны условия розыгрыша и сведения о победителях.</p></QuickActionModal><QuickActionModal label="Изменить" title="Изменить розыгрыш" action="Сохранить"><DrawingForm /></QuickActionModal></div></section>)}</div></AdminPanel>; }
function Milestones() { return <AdminPanel className="p-4"><div className="grid gap-3 lg:grid-cols-2">{milestones.map((item) => <section key={item.id} className="rounded-[8px] border border-[rgb(var(--border))] bg-[rgb(var(--canvas))] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="m-0 text-lg font-black">{item.title}</h2><p className="m-0 mt-1 text-sm font-semibold text-[rgb(var(--text-muted))]">{item.reward} · {item.drivers} водителей в прогрессе</p></div><Status value={item.status} /></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-[rgb(var(--surface))]"><div className="h-full w-[60%] bg-[rgb(var(--primary))]" /></div><QuickActionModal label="Настроить" title="Настройка цели водителя" action="Сохранить"><p>Условия: проверенный водитель, зачётные поездки, без поздних отмен и эскалаций безопасности.</p><p>Состояния «На проверке» и «Отклонено» видны в транзакциях.</p></QuickActionModal></section>)}</div></AdminPanel>; }
function DrawingForm() { return <div className="grid gap-2"><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Приз" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Условия" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Дата начала/окончания" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Стоимость билета / правило участия" /></div>; }
function Summary({ label, value, tone }: { label: string; value: string; tone: "success" | "warning" | "danger" | "info" }) { return <AdminPanel className="p-4"><AdminStatusBadge tone={tone}>{label}</AdminStatusBadge><div className="mt-3 text-3xl font-black">{value}</div></AdminPanel>; }
function StatusLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 rounded-[8px] bg-[rgb(var(--surface))] p-3 text-sm"><span className="font-semibold text-[rgb(var(--text-muted))]">{label}</span><strong className="text-right">{value}</strong></div>; }
