"use client";

import { useMemo, useState } from "react";
import { AdminPageHeader, AdminPanel, AdminStatusBadge } from "../admin-shell";
import { DataTable, QuickActionModal, Status, Tabs, Toolbar } from "../admin-components";
import { rewards } from "../admin-data";

const drawings = [
  { id: "DRAW-01", prize: "500 000 UZS travel certificate", eligibility: "Client reward tickets", window: "10 Jun -> 18 Jun", entries: "1 ticket = 1 entry", participants: 128, winners: "Pending" },
  { id: "DRAW-02", prize: "Driver fuel bonus", eligibility: "30 qualifying trips", window: "20 Jun -> 30 Jun", entries: "10 tickets = 1 entry", participants: 46, winners: "Scheduled" },
];
const milestones = [
  { id: "MS-50", title: "50 qualifying trips", reward: "200 000 UZS", status: "Active", drivers: 34 },
  { id: "MS-Q90", title: "Quality 90 days", reward: "Priority visibility", status: "Review", drivers: 12 },
];

type TabKey = "Overview" | "Drawings" | "Transactions" | "Driver Milestones";

export default function RewardsPage() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All statuses");
  const [activeTab, setActiveTab] = useState<TabKey>("Overview");
  const rows = useMemo(() => rewards.filter((r) => `${r.id} ${r.owner} ${r.role} ${r.source}`.toLowerCase().includes(query.toLowerCase()) && (filter === "All statuses" || r.status === filter || r.role === filter || r.risk === filter)), [filter, query]);

  return <main className="admin-main"><AdminPageHeader title="Rewards" subtitle="Drawings, reward transactions, pending review and driver milestone configuration." actions={<QuickActionModal label="Create drawing" title="Create reward drawing" action="Save drawing"><DrawingForm /></QuickActionModal>} />
    <div className="mb-3 flex flex-wrap gap-2">{(["Overview", "Drawings", "Transactions", "Driver Milestones"] as TabKey[]).map((tab) => <button key={tab} className={`min-h-9 rounded-[10px] px-3 text-sm font-black ${activeTab === tab ? "bg-[rgb(var(--primary))] text-[rgb(var(--primary-foreground))]" : "border border-[rgb(var(--border))] bg-[rgb(var(--surface))] text-[rgb(var(--text-muted))]"}`} type="button" onClick={() => setActiveTab(tab)}>{tab}</button>)}</div>
    {activeTab === "Overview" ? <Overview /> : null}
    {activeTab === "Drawings" ? <Drawings /> : null}
    {activeTab === "Transactions" ? <AdminPanel className="overflow-hidden"><Toolbar query={query} onQuery={setQuery} filters={["All statuses", "Client", "Driver", "Pending", "Approved", "Rejected", "Low", "Medium", "High"]} activeFilter={filter} onFilter={setFilter} placeholder="Reward, user, driver, source" count={rows.length} /><DataTable rows={rows} hrefFor={() => "/rewards"} columns={[{ key: "id", label: "Reward", render: (r) => <strong>{r.id}</strong> }, { key: "owner", label: "Owner", render: (r) => `${r.owner} · ${r.role}` }, { key: "source", label: "Source", render: (r) => r.source }, { key: "trip", label: "Trip", render: (r) => r.tripId }, { key: "amount", label: "Amount", render: (r) => r.amount }, { key: "status", label: "Status", render: (r) => <Status value={r.status} /> }, { key: "risk", label: "Risk", render: (r) => <Status value={r.risk} /> }, { key: "action", label: "Action", render: (r) => <QuickActionModal label="Review" title="Reward transaction"><p>{r.owner} · {r.source} · {r.amount}</p><p>Demo review shows approve/reject context without backend mutation.</p></QuickActionModal> }]} /></AdminPanel> : null}
    {activeTab === "Driver Milestones" ? <Milestones /> : null}
  </main>;
}

function Overview() { return <div className="grid gap-4 xl:grid-cols-4"><Summary label="Active drawings" value="2" tone="info" /><Summary label="Pending review" value="18" tone="warning" /><Summary label="Reward transactions" value="146" tone="success" /><Summary label="Rejected / fraud" value="7" tone="danger" /><AdminPanel className="p-4 xl:col-span-2"><h2 className="m-0 text-lg font-black">Reward operations</h2><p className="text-sm font-semibold text-[rgb(var(--text-muted))]">Overview tracks client tickets, driver points, referral rewards, promo rewards and drawing entries in deterministic preview state.</p><div className="grid gap-2 sm:grid-cols-2"><StatusLine label="Client tickets issued" value="1 284" /><StatusLine label="Driver milestone candidates" value="34" /><StatusLine label="Pending review queue" value="18" /><StatusLine label="Fraud-review rejected" value="7" /></div></AdminPanel><AdminPanel className="p-4 xl:col-span-2"><h2 className="m-0 text-lg font-black">Pending states</h2><div className="mt-3 grid gap-2"><StatusLine label="Spring promo" value="Pending review" /><StatusLine label="Luggage dispute reward" value="Rejected" /><StatusLine label="Driver quality bonus" value="Review" /></div></AdminPanel></div>; }
function Drawings() { return <AdminPanel className="p-4"><div className="grid gap-3 lg:grid-cols-2">{drawings.map((drawing) => <section key={drawing.id} className="rounded-[8px] border border-[rgb(var(--border))] bg-[rgb(var(--canvas))] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="m-0 text-lg font-black">{drawing.prize}</h2><p className="m-0 mt-1 text-sm font-semibold text-[rgb(var(--text-muted))]">{drawing.id} · {drawing.window}</p></div><Status value={drawing.winners} /></div><div className="mt-3 grid gap-2 text-sm"><StatusLine label="Eligibility" value={drawing.eligibility} /><StatusLine label="Ticket rule" value={drawing.entries} /><StatusLine label="Participants" value={String(drawing.participants)} /></div><div className="mt-3 flex gap-2"><QuickActionModal label="Prize detail" title="Prize detail"><p>{drawing.prize}</p><p>Winner selection and notification are mocked for preview.</p></QuickActionModal><QuickActionModal label="Edit" title="Edit drawing" action="Save demo changes"><DrawingForm /></QuickActionModal></div></section>)}</div></AdminPanel>; }
function Milestones() { return <AdminPanel className="p-4"><div className="grid gap-3 lg:grid-cols-2">{milestones.map((item) => <section key={item.id} className="rounded-[8px] border border-[rgb(var(--border))] bg-[rgb(var(--canvas))] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="m-0 text-lg font-black">{item.title}</h2><p className="m-0 mt-1 text-sm font-semibold text-[rgb(var(--text-muted))]">{item.reward} · {item.drivers} drivers in progress</p></div><Status value={item.status} /></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-[rgb(var(--surface))]"><div className="h-full w-[60%] bg-[rgb(var(--primary))]" /></div><QuickActionModal label="Configure" title="Driver milestone configuration" action="Save config"><p>Eligibility: verified driver, qualifying trips, no late cancel streak break and no safety escalation.</p><p>Pending/rejected states are visible in transactions.</p></QuickActionModal></section>)}</div></AdminPanel>; }
function DrawingForm() { return <div className="grid gap-2"><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Prize" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Eligibility" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Start/end date" /><input className="min-h-10 rounded-[10px] border border-[rgb(var(--border))] px-3" defaultValue="Ticket cost / entry rule" /></div>; }
function Summary({ label, value, tone }: { label: string; value: string; tone: "success" | "warning" | "danger" | "info" }) { return <AdminPanel className="p-4"><AdminStatusBadge tone={tone}>{label}</AdminStatusBadge><div className="mt-3 text-3xl font-black">{value}</div></AdminPanel>; }
function StatusLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 rounded-[8px] bg-[rgb(var(--surface))] p-3 text-sm"><span className="font-semibold text-[rgb(var(--text-muted))]">{label}</span><strong className="text-right">{value}</strong></div>; }
